name: Qbeats
description: Smart Metronome APP
publish_to: "none"

version: 1.2.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_soloud: ^3.4.10
  shared_preferences: ^2.2.3
  wakelock_plus: ^1.2.8
  audio_session: ^0.1.18
  flutter_launcher_icons: ^0.13.1
  google_mobile_ads: ^7.0.0
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/light/
    - assets/icons/dark/
    - assets/sound/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: assets/img/icon.png
  min_sdk_android: 21